// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBQ_mgfqh0kzk1eK1nKnfeVWLc1_OpUGo',
    appId: '1:551640274053:web:6f29a25f7418ffdd07c5ec',
    messagingSenderId: '551640274053',
    projectId: 'shop-shpere',
    authDomain: 'shop-shpere.firebaseapp.com',
    storageBucket: 'shop-shpere.firebasestorage.app',
    measurementId: 'G-0SC31YRVFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGP_EjF25NeicY6292wwfTGdPrfFfaoj8',
    appId: '1:551640274053:android:75edf25b5379da5707c5ec',
    messagingSenderId: '551640274053',
    projectId: 'shop-shpere',
    storageBucket: 'shop-shpere.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARx2CQUhdZvmopBoYvLkbv1LDRtJHBXsI',
    appId: '1:551640274053:ios:6468c47fba5e60fa07c5ec',
    messagingSenderId: '551640274053',
    projectId: 'shop-shpere',
    storageBucket: 'shop-shpere.firebasestorage.app',
    iosBundleId: 'com.example.shopSphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARx2CQUhdZvmopBoYvLkbv1LDRtJHBXsI',
    appId: '1:551640274053:ios:6468c47fba5e60fa07c5ec',
    messagingSenderId: '551640274053',
    projectId: 'shop-shpere',
    storageBucket: 'shop-shpere.firebasestorage.app',
    iosBundleId: 'com.example.shopSphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBQ_mgfqh0kzk1eK1nKnfeVWLc1_OpUGo',
    appId: '1:551640274053:web:b956014bc1182acd07c5ec',
    messagingSenderId: '551640274053',
    projectId: 'shop-shpere',
    authDomain: 'shop-shpere.firebaseapp.com',
    storageBucket: 'shop-shpere.firebasestorage.app',
    measurementId: 'G-H96CVVQ2DM',
  );
}
